In [2]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


2.10.0+cpu
False


In [3]:
print(torch.cuda.is_available())

False


Creating a Tensor

In [4]:
# using empty
a=torch.empty(2,3)
print(a)

tensor([[9.9381e-32, 1.4798e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
# check type
type(a)

torch.Tensor

In [6]:
# using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# using rand
torch.rand(2,3)

tensor([[0.0455, 0.6966, 0.2110],
        [0.6752, 0.0102, 0.4361]])

In [9]:
# use of seed
torch.rand(2,3)

tensor([[0.3993, 0.1919, 0.9441],
        [0.9500, 0.7910, 0.7966]])

In [10]:
# manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
# arange
print("using arange ->", torch.arange(0,10,2))

using arange -> tensor([0, 2, 4, 6, 8])


In [14]:
# using linspace
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [15]:
# using eye
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [16]:
# using full
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

Tensor Shapes

In [17]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
x.shape

torch.Size([2, 3])

In [19]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [20]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [22]:
torch.rand_like(x,dtype=torch.float64)

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

Tensor Data Types

In [23]:
# find data type
x.dtype

torch.int64

In [24]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [25]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [26]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical Operations

1. Scalar Operation

In [27]:
x=torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [28]:
# addition
x+2

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])

In [29]:
# subtraction
x-2

tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])

In [30]:
# multiplication
x*2

tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])

In [31]:
# division
x/3

tensor([[0.0746, 0.1008],
        [0.0595, 0.2746]])

In [32]:
# int division
(x*100)//3

tensor([[ 7., 10.],
        [ 5., 27.]])

In [33]:
# mod
((x*100)//3)%2

tensor([[1., 0.],
        [1., 1.]])

In [34]:
# power
x**2

tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])

2. Element Wise Operation

In [35]:
a=torch.rand(2,3)
b=torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [36]:
#add
a+b

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])

In [37]:
# sub
a-b

tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])

In [38]:
# multiply
a*b

tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])

In [39]:
# division
a/b

tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])

In [40]:
# mod
a%b

tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])

In [41]:
c= torch.tensor([1,-2,3,-4])

In [42]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [43]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [44]:
d=torch.tensor([1.9,2.3,3.7,4.4])

In [45]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [46]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [47]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [48]:
# clamp
torch.clamp(d, min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3. Reduction Operation

In [49]:
e=torch.randint(size=(2,3),low=0,high=10)
e

tensor([[5, 7, 3],
        [9, 4, 0]])

In [50]:
# sum
torch.sum(e)

tensor(28)

In [51]:
# sum along columns
torch.sum(e,dim=0)

tensor([14, 11,  3])

In [52]:
# sum along rows
torch.sum(e,dim=1)

tensor([15, 13])

In [53]:
e=torch.randint(size=(2,3),low=0,high=10, dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [54]:
# mean
torch.mean(e)

tensor(7.)

In [55]:
torch.mean(e, dim=1)

tensor([5.6667, 8.3333])

In [56]:
# median
torch.median(e)

tensor(7.)

In [57]:
# max and min
torch.max(e)


tensor(9.)

In [58]:
torch.min(e)

tensor(5.)

In [59]:
# product
torch.prod(e)

tensor(99225.)

In [60]:
# standar deviation
torch.std(e)

tensor(1.7889)

In [61]:
# variace
torch.var(e)

tensor(3.2000)

In [62]:
# argmax
torch.argmax(e)

tensor(3)

In [63]:
# argmin
torch.argmin(e)

tensor(0)

4. Matrix Operations

In [64]:
f=torch.randint(size=(2,3), low=0, high=10)
g=torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [65]:
# matrix multiplication
torch.matmul(f,g)

tensor([[137, 117],
        [139, 130]])

In [66]:
vector1 = torch.tensor([1,4])
vector2 = torch.tensor([3,4])

# dot product
torch.dot(vector1, vector2)

tensor(19)

In [67]:
# transpose
f
torch.transpose(f,0,1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [68]:
h=torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[6., 1., 5.],
        [5., 0., 4.],
        [3., 8., 8.]])

In [69]:
# determinant
torch.det(h)

tensor(-20.0000)

In [70]:
# inverse
torch.inverse(h)

tensor([[ 1.6000, -1.6000, -0.2000],
        [ 1.4000, -1.6500, -0.0500],
        [-2.0000,  2.2500,  0.2500]])

5. Comparison Operation

In [71]:
i=torch.randint(size=(3,2), low=0, high=10)
j=torch.randint(size=(3,2), low=0, high=10)

In [72]:
# greater than
i>j

tensor([[ True, False],
        [ True, False],
        [ True,  True]])

In [73]:
# less than
i<j

tensor([[False,  True],
        [False,  True],
        [False, False]])

In [74]:
# equal to
i==j

tensor([[False, False],
        [False, False],
        [False, False]])

6. Special Functions

In [75]:
k=torch.randint(size=(3,2), low=0, high=10)
k

tensor([[8, 5],
        [6, 2],
        [9, 5]])

In [76]:
# log
torch.log(k)

tensor([[2.0794, 1.6094],
        [1.7918, 0.6931],
        [2.1972, 1.6094]])

In [77]:
# exp
torch.exp(k)

tensor([[2.9810e+03, 1.4841e+02],
        [4.0343e+02, 7.3891e+00],
        [8.1031e+03, 1.4841e+02]])

In [78]:
# sqrt
torch.sqrt(k)

tensor([[2.8284, 2.2361],
        [2.4495, 1.4142],
        [3.0000, 2.2361]])

In [79]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9997, 0.9933],
        [0.9975, 0.8808],
        [0.9999, 0.9933]])

In [80]:
# softmax
l=torch.randint(size=(3,2), low=0, high=10, dtype=torch.float32)
torch.softmax(l, dim=0)

tensor([[0.0900, 0.0473],
        [0.6652, 0.9503],
        [0.2447, 0.0024]])

In [81]:
# relu
torch.relu(k)

tensor([[8, 5],
        [6, 2],
        [9, 5]])

7. Inplace Operations

In [82]:
m=torch.rand(2,3)
n=torch.rand(2,3)
print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [83]:
m.add_(n)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [84]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [85]:
n

tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])

In [86]:
torch.relu(m)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [87]:
m.relu_()

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [88]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

Copying a Tensor

In [89]:
a=torch.rand(2,3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [90]:
b=a
b

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [91]:
a[0][0]=0
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [92]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [93]:
id(a)

2003083225488

In [94]:
id(b)

2003083225488

In [95]:
b=a.clone()

In [96]:
a

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [97]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [98]:
a[0][0]=10
a

tensor([[10.0000,  0.0340,  0.9157],
        [ 0.3079,  0.6269,  0.8277]])

In [99]:
b

tensor([[0.0000, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [100]:
id(a)

2003083225488

In [101]:
id(b)

2003087633744

Tensor Operations on GPU

In [102]:
torch.cuda.is_available()

False

In [103]:
device=torch.device('cuda')

In [104]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

AssertionError: Torch not compiled with CUDA enabled

In [ ]:
# moving an existing tensor to GPU
b=a.to(device)

Reshaping tensors

In [105]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [107]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [108]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [110]:
b=torch.rand(2,3,4)
b

tensor([[[0.5534, 0.2682, 0.9556, 0.9761],
         [0.5934, 0.3124, 0.9431, 0.8519],
         [0.9815, 0.1132, 0.4783, 0.4436]],

        [[0.3847, 0.4521, 0.5569, 0.9952],
         [0.0015, 0.0813, 0.4907, 0.2130],
         [0.4603, 0.1386, 0.0277, 0.5662]]])

In [113]:
# permute
b.permute(2,0,1).shape

torch.Size([4, 2, 3])

In [114]:
# unsqueeze
# image size
c=torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [115]:
# squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

NumPy and PyTorch

In [116]:
import numpy as np

In [118]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [119]:
b=a.numpy()
b

array([1, 2, 3])

In [120]:
type(b)

numpy.ndarray

In [122]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [123]:
torch.from_numpy(c)

tensor([1, 2, 3])