In [1]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear=nn.Linear(num_features,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out

In [2]:
# create dataset
features=torch.rand(10,5)

#create model
model=Model(features.shape[1])

#call model for forward pass
model(features)

tensor([[0.4361],
        [0.4237],
        [0.4321],
        [0.3608],
        [0.4261],
        [0.4154],
        [0.3682],
        [0.3871],
        [0.3563],
        [0.3198]], grad_fn=<SigmoidBackward0>)

In [3]:
#show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.2107, -0.1312, -0.4121,  0.0638,  0.1212]], requires_grad=True)

In [4]:
import sys
!{sys.executable} -m pip install torchinfo

In [5]:
from torchinfo import summary

summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

With one Hidden Layer

In [6]:
class Model2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features,3)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(3,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)

        return out

In [7]:
# create dataset
features=torch.rand(10,5)

#create model
model2=Model2(features.shape[1])

#call model for forward pass
model2(features)

tensor([[0.6174],
        [0.6174],
        [0.6174],
        [0.6198],
        [0.6174],
        [0.6288],
        [0.6174],
        [0.6174],
        [0.6174],
        [0.6174]], grad_fn=<SigmoidBackward0>)

In [8]:
model2.linear1.weight

Parameter containing:
tensor([[-0.4336, -0.0135,  0.0484,  0.0046, -0.0605],
        [ 0.0730, -0.0010, -0.1810, -0.2967, -0.3268],
        [ 0.4366,  0.0074, -0.4178, -0.0349, -0.1473]], requires_grad=True)

In [9]:
summary(model2,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Sequential Container Modules

In [10]:
class Model2(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid(),
        )
       

    def forward(self, features):
        out=self.network(features)
        
        return out

In [11]:
# create dataset
features=torch.rand(10,5)

#create model
model2=Model2(features.shape[1])

#call model for forward pass
model2(features)

tensor([[0.3691],
        [0.3691],
        [0.3691],
        [0.3691],
        [0.3691],
        [0.3691],
        [0.3691],
        [0.3691],
        [0.3691],
        [0.3691]], grad_fn=<SigmoidBackward0>)