In [25]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [26]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [27]:
df.shape

(569, 33)

In [28]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

Train Test split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

Scaling

In [32]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [33]:
X_train

array([[ 1.35710597e+00,  8.12378010e-01,  1.38055268e+00, ...,
         8.25008518e-01,  4.47228999e-01,  4.39159548e-01],
       [-1.07581275e+00, -7.13498072e-01, -1.02509082e+00, ...,
        -2.71281057e-01, -4.90125260e-01,  7.03144032e-01],
       [-9.04173464e-01, -8.48916551e-01, -8.71631441e-01, ...,
        -5.36984828e-01, -5.33387765e-01,  1.30575310e+00],
       ...,
       [-2.88451595e-01,  3.89195261e-01, -2.57399407e-01, ...,
         3.74613447e-02, -5.62229434e-01, -1.35459485e-01],
       [ 9.02445993e-02,  5.06490624e-02,  6.88497202e-02, ...,
        -2.93697011e-01, -7.09642412e-01, -5.25673556e-01],
       [ 3.84803714e-02, -1.36882679e+00,  2.07219372e-04, ...,
        -1.03011965e-01,  2.37325738e-01, -1.28908814e+00]],
      shape=(455, 30))

In [34]:
y_train

198    M
320    B
474    B
554    B
273    B
      ..
430    M
504    B
466    B
448    B
225    B
Name: diagnosis, Length: 455, dtype: str

Label Encoding

In [35]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [36]:
y_train

array([1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0,

Numpy Arrays to PyTorch Tensors

In [38]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [39]:
X_train_tensor.shape

torch.Size([455, 30])

In [40]:
y_train_tensor.shape

torch.Size([455])

Defining the Model

In [41]:
from torch.utils.data import Dataset, DataLoader

class CustomDataset(Dataset):

    def __init__(self,  features, labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return self.features.shape[0]

    def  __getitem__(self,index):
        return self.features[index], self.labels[index]

In [43]:
train_dataset= CustomDataset(X_train_tensor, y_train_tensor)
test_dataset= CustomDataset(X_test_tensor, y_test_tensor)

In [44]:
train_dataset[10]

(tensor([-0.0433, -0.7619, -0.1075, -0.1443, -0.8877, -0.8603, -0.6731, -0.5131,
         -0.3785, -0.5477, -0.0748, -0.2984, -0.1212, -0.1798,  0.3018, -0.7032,
         -0.5120, -0.4447, -0.0739, -0.3705, -0.1374, -0.6582, -0.1901, -0.2427,
         -0.6070, -0.8219, -0.7682, -0.6136, -0.3027, -0.6514]),
 tensor(0.))

In [45]:
train_loader=DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader=DataLoader(test_dataset, batch_size=32, shuffle=True)

PyTorch NN Model

In [47]:
import torch.nn as nn

class MysimpleNN(nn.Module):

    def __init__(self, num_features):
        super().__init__()
        self.linear=nn.Linear(num_features, 1)
        self.sigmoid=nn.Sigmoid()

    def forward(self, features):
        out=self.linear(features)
        out=self.sigmoid(out)

        return out

Important Parameters

In [48]:
learning_rate=0.1
epochs=25

In [50]:
# create model
model= MysimpleNN(X_train_tensor.shape[1])

#define optimizer
optimizer= torch.optim.SGD(model.parameters(), lr=learning_rate)

#define loss function
loss_function= nn.BCELoss()

Training Pipeline

In [51]:
#define loop
for epoch in range(epochs):

    for batch_features, batch_labels in train_loader:
        
        #forward pass
        y_pred=model(batch_features)
       
    
        #loss calculate
        loss=loss_function(y_pred, batch_labels.view(-1,1))

        #clear gradients
        optimizer.zero_grad()
    
        # backward pass
        loss.backward()
    
        #parameters update
        optimizer.step()
        
        #print loss in each epoch
        print(f'Epoch: {epoch+1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.7065240740776062
Epoch: 1, Loss: 0.5866965651512146
Epoch: 1, Loss: 0.36697325110435486
Epoch: 1, Loss: 0.520470142364502
Epoch: 1, Loss: 0.3535498380661011
Epoch: 1, Loss: 0.4314877390861511
Epoch: 1, Loss: 0.3591374158859253
Epoch: 1, Loss: 0.2908216416835785
Epoch: 1, Loss: 0.2306472212076187
Epoch: 1, Loss: 0.3016655743122101
Epoch: 1, Loss: 0.22064097225666046
Epoch: 1, Loss: 0.20534725487232208
Epoch: 1, Loss: 0.17815136909484863
Epoch: 1, Loss: 0.27580708265304565
Epoch: 1, Loss: 0.17383186519145966
Epoch: 2, Loss: 0.20540423691272736
Epoch: 2, Loss: 0.14280901849269867
Epoch: 2, Loss: 0.2159879207611084
Epoch: 2, Loss: 0.17034819722175598
Epoch: 2, Loss: 0.19961652159690857
Epoch: 2, Loss: 0.21753349900245667
Epoch: 2, Loss: 0.2128153145313263
Epoch: 2, Loss: 0.19166138768196106
Epoch: 2, Loss: 0.11857067048549652
Epoch: 2, Loss: 0.16610412299633026
Epoch: 2, Loss: 0.22669263184070587
Epoch: 2, Loss: 0.13197211921215057
Epoch: 2, Loss: 0.09802901744842529
Epoc

In [52]:
# Model evaluation using test_loader
model.eval()  # Set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:
        # Forward pass
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.8).float()  # Convert probabilities to binary predictions

        # Calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)

# Calculate overall accuracy
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f'Accuracy: {overall_accuracy:.4f}')


Accuracy: 0.9080
